name: my_member_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animated_switch: ^0.0.3
  email_validator: ^3.0.0
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  http: ^1.2.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.2
  email_auth: ^2.0.0
  email_otp: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/animation/Animation1.json
  - assets/images/logo2.png
  - assets/images/googlelogo.png
  - assets/images/facebooklogo.png
  - assets/animation/robot.json