name: my_assignment_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_any_logo: ^1.1.1
  http: ^1.2.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/animation/Animation1.json
  - assets/images/logo2.png
